### ISSUE TITLE
Issue querying all records

### ISSUE THREAD

**Issue by rdrop** [minimul/qbo_api#32] opened 2017-08-28 18:48 UTC
When running:

`qbo_api.all(:customers).each do |c|`
    `     p "#{c['Id']} #{c['DisplayName']}"`
` end`

The following error is returned in the console:

`LocalJumpError: no block given (yield)`

**Comment by minimul** [comment] 2017-08-29 14:34
I'm not able to reproduce.

**Comment by ntippie** [comment] 2017-09-07 00:06
You should pass the block directly to the #all method, not to #each:

```ruby
qbo_api.all(:customers) do |c|
  p "#{c['Id']} #{c['DisplayName']}"
end
```

**Comment by minimul** [comment] 2017-09-12 13:30
Yes, but `.each` does work as well. Closing.

**Closed by minimul** 2017-09-12 13:30 UTC
